LOCAL_PATH := $(call my-dir)

include $(CLEAR_VARS)

LOCAL_MODULE    := unwind

LOCAL_CFLAGS += -DHAVE_CONFIG_H

LOCAL_C_INCLUDES := ./include

LOCAL_SRC_FILES :=  \
           ./src/arm/Gcreate_addr_space.c \
           ./src/arm/gen-offsets.c \
           ./src/arm/Gex_tables.c \
           ./src/arm/Gget_proc_info.c \
           ./src/arm/Gget_save_loc.c \
           ./src/arm/Gglobal.c \
           ./src/arm/Ginit.c \
           ./src/arm/Ginit_local.c \
           ./src/arm/Ginit_remote.c \
           ./src/arm/Gis_signal_frame.c \
           ./src/arm/Gregs.c \
           ./src/arm/Gresume.c \
           ./src/arm/Gstep.c \
           ./src/arm/is_fpreg.c \
           ./src/arm/Lcreate_addr_space.c \
           ./src/arm/Lex_tables.c \
           ./src/arm/Lget_proc_info.c \
           ./src/arm/Lget_save_loc.c \
           ./src/arm/Lglobal.c \
           ./src/arm/Linit.c \
           ./src/arm/Linit_local.c \
           ./src/arm/Linit_remote.c \
           ./src/arm/Lis_signal_frame.c \
           ./src/arm/Lregs.c \
           ./src/arm/Lresume.c \
           ./src/arm/Lstep.c \
           ./src/arm/regname.c \
           ./src/coredump/_UCD_access_mem.c \
           ./src/coredump/_UCD_access_reg_freebsd.c \
           ./src/coredump/_UCD_access_reg_linux.c \
           ./src/coredump/_UCD_accessors.c \
           ./src/coredump/_UCD_create.c \
           ./src/coredump/_UCD_destroy.c \
           ./src/coredump/_UCD_elf_map_image.c \
           ./src/coredump/_UCD_find_proc_info.c \
           ./src/coredump/_UCD_get_proc_name.c \
           ./src/coredump/_UPT_access_fpreg.c \
           ./src/coredump/_UPT_elf.c \
           ./src/coredump/_UPT_get_dyn_info_list_addr.c \
           ./src/coredump/_UPT_put_unwind_info.c \
           ./src/coredump/_UPT_resume.c \
           ./src/dwarf/Gexpr.c \
           ./src/dwarf/Gfde.c \
           ./src/dwarf/Gfind_proc_info-lsb.c \
           ./src/dwarf/Gfind_unwind_table.c \
           ./src/dwarf/global.c \
           ./src/dwarf/Gparser.c \
           ./src/dwarf/Gpe.c \
           ./src/dwarf/Gstep.c \
           ./src/dwarf/Lexpr.c \
           ./src/dwarf/Lfde.c \
           ./src/dwarf/Lfind_proc_info-lsb.c \
           ./src/dwarf/Lfind_unwind_table.c \
           ./src/dwarf/Lparser.c \
           ./src/dwarf/Lpe.c \
           ./src/dwarf/Lstep.c \
           ./src/elf32.c \
           ./src/elf64.c \
           ./src/elfxx.c \
           ./src/hppa/Gcreate_addr_space.c \
           ./src/hppa/get_accessors.c \
           ./src/hppa/Gget_proc_info.c \
           ./src/hppa/Gget_save_loc.c \
           ./src/hppa/Gglobal.c \
           ./src/hppa/Ginit.c \
           ./src/hppa/Ginit_local.c \
           ./src/hppa/Ginit_remote.c \
           ./src/hppa/Gis_signal_frame.c \
           ./src/hppa/Gregs.c \
           ./src/hppa/Gresume.c \
           ./src/hppa/Gstep.c \
           ./src/hppa/Lcreate_addr_space.c \
           ./src/hppa/Lget_proc_info.c \
           ./src/hppa/Lget_save_loc.c \
           ./src/hppa/Lglobal.c \
           ./src/hppa/Linit.c \
           ./src/hppa/Linit_local.c \
           ./src/hppa/Linit_remote.c \
           ./src/hppa/Lis_signal_frame.c \
           ./src/hppa/Lregs.c \
           ./src/hppa/Lresume.c \
           ./src/hppa/Lstep.c \
           ./src/hppa/regname.c \
           ./src/hppa/tables.c \
           ./src/ia64/Gcreate_addr_space.c \
           ./src/ia64/Gfind_unwind_table.c \
           ./src/ia64/Gget_proc_info.c \
           ./src/ia64/Gget_save_loc.c \
           ./src/ia64/Gglobal.c \
           ./src/ia64/Ginit.c \
           ./src/ia64/Ginit_local.c \
           ./src/ia64/Ginit_remote.c \
           ./src/ia64/Gis_signal_frame.c \
           ./src/ia64/Gparser.c \
           ./src/ia64/Grbs.c \
           ./src/ia64/Gregs.c \
           ./src/ia64/Gresume.c \
           ./src/ia64/Gscript.c \
           ./src/ia64/Gstep.c \
           ./src/ia64/Gtables.c \
           ./src/ia64/Lcreate_addr_space.c \
           ./src/ia64/Lfind_unwind_table.c \
           ./src/ia64/Lget_proc_info.c \
           ./src/ia64/Lget_save_loc.c \
           ./src/ia64/Lglobal.c \
           ./src/ia64/Linit.c \
           ./src/ia64/Linit_local.c \
           ./src/ia64/Linit_remote.c \
           ./src/ia64/Lis_signal_frame.c \
           ./src/ia64/Lparser.c \
           ./src/ia64/Lrbs.c \
           ./src/ia64/Lregs.c \
           ./src/ia64/Lresume.c \
           ./src/ia64/Lscript.c \
           ./src/ia64/Lstep.c \
           ./src/ia64/Ltables.c \
           ./src/ia64/mk_Gcursor_i.c \
           ./src/ia64/mk_Lcursor_i.c \
           ./src/ia64/regname.c \
           ./src/mi/_ReadSLEB.c \
           ./src/mi/_ReadULEB.c \
           ./src/mi/backtrace.c \
           ./src/mi/dyn-cancel.c \
           ./src/mi/dyn-info-list.c \
           ./src/mi/dyn-register.c \
           ./src/mi/flush_cache.c \
           ./src/mi/Gdestroy_addr_space.c \
           ./src/mi/Gdyn-extract.c \
           ./src/mi/Gdyn-remote.c \
           ./src/mi/Gfind_dynamic_proc_info.c \
           ./src/mi/Gget_accessors.c \
           ./src/mi/Gget_fpreg.c \
           ./src/mi/Gget_proc_info_by_ip.c \
           ./src/mi/Gget_proc_name.c \
           ./src/mi/Gget_reg.c \
           ./src/mi/Gput_dynamic_unwind_info.c \
           ./src/mi/Gset_caching_policy.c \
           ./src/mi/Gset_fpreg.c \
           ./src/mi/Gset_reg.c \
           ./src/mi/init.c \
           ./src/mi/Ldestroy_addr_space.c \
           ./src/mi/Ldyn-extract.c \
           ./src/mi/Ldyn-remote.c \
           ./src/mi/Lfind_dynamic_proc_info.c \
           ./src/mi/Lget_accessors.c \
           ./src/mi/Lget_fpreg.c \
           ./src/mi/Lget_proc_info_by_ip.c \
           ./src/mi/Lget_proc_name.c \
           ./src/mi/Lget_reg.c \
           ./src/mi/Lput_dynamic_unwind_info.c \
           ./src/mi/Lset_caching_policy.c \
           ./src/mi/Lset_fpreg.c \
           ./src/mi/Lset_reg.c \
           ./src/mi/mempool.c \
           ./src/mi/strerror.c \
           ./src/mips/elfxx.c \
           ./src/mips/Gcreate_addr_space.c \
           ./src/mips/gen-offsets.c \
           ./src/mips/Gget_proc_info.c \
           ./src/mips/Gget_save_loc.c \
           ./src/mips/Gglobal.c \
           ./src/mips/Ginit.c \
           ./src/mips/Ginit_local.c \
           ./src/mips/Ginit_remote.c \
           ./src/mips/Gis_signal_frame.c \
           ./src/mips/Gregs.c \
           ./src/mips/Gresume.c \
           ./src/mips/Gstep.c \
           ./src/mips/is_fpreg.c \
           ./src/mips/Lcreate_addr_space.c \
           ./src/mips/Lget_proc_info.c \
           ./src/mips/Lget_save_loc.c \
           ./src/mips/Lglobal.c \
           ./src/mips/Linit.c \
           ./src/mips/Linit_local.c \
           ./src/mips/Linit_remote.c \
           ./src/mips/Lis_signal_frame.c \
           ./src/mips/Lregs.c \
           ./src/mips/Lresume.c \
           ./src/mips/Lstep.c \
           ./src/mips/regname.c \
           ./src/os-freebsd.c \
           ./src/os-hpux.c \
           ./src/os-linux.c \
           ./src/ppc/Gcreate_addr_space.c \
           ./src/ppc/Gget_proc_info.c \
           ./src/ppc/Gget_save_loc.c \
           ./src/ppc/Ginit_local.c \
           ./src/ppc/Ginit_remote.c \
           ./src/ppc/Gis_signal_frame.c \
           ./src/ppc/Lcreate_addr_space.c \
           ./src/ppc/Lget_proc_info.c \
           ./src/ppc/Lget_save_loc.c \
           ./src/ppc/Linit_local.c \
           ./src/ppc/Linit_remote.c \
           ./src/ppc/Lis_signal_frame.c \
           ./src/ppc32/get_func_addr.c \
           ./src/ppc32/Gglobal.c \
           ./src/ppc32/Ginit.c \
           ./src/ppc32/Gregs.c \
           ./src/ppc32/Gresume.c \
           ./src/ppc32/Gstep.c \
           ./src/ppc32/is_fpreg.c \
           ./src/ppc32/Lglobal.c \
           ./src/ppc32/Linit.c \
           ./src/ppc32/Lregs.c \
           ./src/ppc32/Lresume.c \
           ./src/ppc32/Lstep.c \
           ./src/ppc32/regname.c \
           ./src/ppc64/get_func_addr.c \
           ./src/ppc64/Gglobal.c \
           ./src/ppc64/Ginit.c \
           ./src/ppc64/Gregs.c \
           ./src/ppc64/Gresume.c \
           ./src/ppc64/Gstep.c \
           ./src/ppc64/is_fpreg.c \
           ./src/ppc64/Lglobal.c \
           ./src/ppc64/Linit.c \
           ./src/ppc64/Lregs.c \
           ./src/ppc64/Lresume.c \
           ./src/ppc64/Lstep.c \
           ./src/ppc64/regname.c \
           ./src/ptrace/_UPT_access_fpreg.c \
           ./src/ptrace/_UPT_access_mem.c \
           ./src/ptrace/_UPT_access_reg.c \
           ./src/ptrace/_UPT_accessors.c \
           ./src/ptrace/_UPT_create.c \
           ./src/ptrace/_UPT_destroy.c \
           ./src/ptrace/_UPT_elf.c \
           ./src/ptrace/_UPT_find_proc_info.c \
           ./src/ptrace/_UPT_get_dyn_info_list_addr.c \
           ./src/ptrace/_UPT_get_proc_name.c \
           ./src/ptrace/_UPT_put_unwind_info.c \
           ./src/ptrace/_UPT_reg_offset.c \
           ./src/ptrace/_UPT_resume.c \
           ./src/setjmp/longjmp.c \
           ./src/setjmp/setjmp.c \
           ./src/setjmp/siglongjmp.c \
           ./src/setjmp/sigsetjmp.c \
           ./src/sh/Gcreate_addr_space.c \
           ./src/sh/gen-offsets.c \
           ./src/sh/Gget_proc_info.c \
           ./src/sh/Gget_save_loc.c \
           ./src/sh/Gglobal.c \
           ./src/sh/Ginit.c \
           ./src/sh/Ginit_local.c \
           ./src/sh/Ginit_remote.c \
           ./src/sh/Gis_signal_frame.c \
           ./src/sh/Gregs.c \
           ./src/sh/Gresume.c \
           ./src/sh/Gstep.c \
           ./src/sh/is_fpreg.c \
           ./src/sh/Lcreate_addr_space.c \
           ./src/sh/Lget_proc_info.c \
           ./src/sh/Lget_save_loc.c \
           ./src/sh/Lglobal.c \
           ./src/sh/Linit.c \
           ./src/sh/Linit_local.c \
           ./src/sh/Linit_remote.c \
           ./src/sh/Lis_signal_frame.c \
           ./src/sh/Lregs.c \
           ./src/sh/Lresume.c \
           ./src/sh/Lstep.c \
           ./src/sh/regname.c \
           ./src/unwind/Backtrace.c \
           ./src/unwind/DeleteException.c \
           ./src/unwind/FindEnclosingFunction.c \
           ./src/unwind/ForcedUnwind.c \
           ./src/unwind/GetBSP.c \
           ./src/unwind/GetCFA.c \
           ./src/unwind/GetDataRelBase.c \
           ./src/unwind/GetGR.c \
           ./src/unwind/GetIP.c \
           ./src/unwind/GetIPInfo.c \
           ./src/unwind/GetLanguageSpecificData.c \
           ./src/unwind/GetRegionStart.c \
           ./src/unwind/GetTextRelBase.c \
           ./src/unwind/RaiseException.c \
           ./src/unwind/Resume.c \
           ./src/unwind/Resume_or_Rethrow.c \
           ./src/unwind/SetGR.c \
           ./src/unwind/SetIP.c \
           ./src/x86/Gcreate_addr_space.c \
           ./src/x86/Gget_proc_info.c \
           ./src/x86/Gget_save_loc.c \
           ./src/x86/Gglobal.c \
           ./src/x86/Ginit.c \
           ./src/x86/Ginit_local.c \
           ./src/x86/Ginit_remote.c \
           ./src/x86/Gos-freebsd.c \
           ./src/x86/Gos-linux.c \
           ./src/x86/Gregs.c \
           ./src/x86/Gresume.c \
           ./src/x86/Gstep.c \
           ./src/x86/is_fpreg.c \
           ./src/x86/Lcreate_addr_space.c \
           ./src/x86/Lget_proc_info.c \
           ./src/x86/Lget_save_loc.c \
           ./src/x86/Lglobal.c \
           ./src/x86/Linit.c \
           ./src/x86/Linit_local.c \
           ./src/x86/Linit_remote.c \
           ./src/x86/Los-freebsd.c \
           ./src/x86/Los-linux.c \
           ./src/x86/Lregs.c \
           ./src/x86/Lresume.c \
           ./src/x86/Lstep.c \
           ./src/x86/regname.c \
           ./src/x86_64/Gcreate_addr_space.c \
           ./src/x86_64/Gget_proc_info.c \
           ./src/x86_64/Gget_save_loc.c \
           ./src/x86_64/Gglobal.c \
           ./src/x86_64/Ginit.c \
           ./src/x86_64/Ginit_local.c \
           ./src/x86_64/Ginit_remote.c \
           ./src/x86_64/Gos-freebsd.c \
           ./src/x86_64/Gos-linux.c \
           ./src/x86_64/Gregs.c \
           ./src/x86_64/Gresume.c \
           ./src/x86_64/Gstash_frame.c \
           ./src/x86_64/Gstep.c \
           ./src/x86_64/Gtrace.c \
           ./src/x86_64/is_fpreg.c \
           ./src/x86_64/Lcreate_addr_space.c \
           ./src/x86_64/Lget_proc_info.c \
           ./src/x86_64/Lget_save_loc.c \
           ./src/x86_64/Lglobal.c \
           ./src/x86_64/Linit.c \
           ./src/x86_64/Linit_local.c \
           ./src/x86_64/Linit_remote.c \
           ./src/x86_64/Los-freebsd.c \
           ./src/x86_64/Los-linux.c \
           ./src/x86_64/Lregs.c \
           ./src/x86_64/Lresume.c \
           ./src/x86_64/Lstash_frame.c \
           ./src/x86_64/Lstep.c \
           ./src/x86_64/Ltrace.c \
           ./src/x86_64/regname.c



include $(BUILD_STATIC_LIBRARY)
